name = "ManagedProperties"
uuid = "5c25fbc6-c823-4e8d-82ee-a726f35d2972"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.2.2"

[deps]
Clocks = "6b5ade5d-6e95-4584-b343-73eec2e8782b"

[compat]
Clocks = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
