name = "ManagedProperties"
uuid = "5c25fbc6-c823-4e8d-82ee-a726f35d2972"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.1.0"

[deps]
Clocks = "6b5ade5d-6e95-4584-b343-73eec2e8782b"

[compat]
Clocks = "0.1.4"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
